name: Site23Skin
version: '${project.version}'
main: fr.lucascha.site23skin.Site23SkinPlugin
api-version: '1.21'
description: Skins par grade pour serveur SCP – Site 23
authors: [ LucasCha ]
depend: [ SkinsRestorer ]

commands:
  skingrade:
    description: Applique le skin du grade à un joueur
    usage: /skingrade <joueur> <grade>
    permission: site23skin.skingrade
  skinretirer:
    description: Retire le skin de grade et restaure le skin original
    usage: /skinretirer <joueur>
    permission: site23skin.retirer
  skinreload:
    description: Recharge la configuration
    usage: /skinreload
    permission: site23skin.reload
  skininfo:
    description: Affiche le grade actuel d'un joueur
    usage: /skininfo [joueur]
    permission: site23skin.info
  espawn:
    description: Restaure le skin Mojang original (skin du compte MC)
    usage: /espawn [joueur]
    permission: site23skin.espawn

permissions:
  site23skin.skingrade:
    description: Appliquer un skin de grade
    default: op
  site23skin.retirer:
    description: Retirer un skin de grade
    default: op
  site23skin.reload:
    description: Recharger la config
    default: op
  site23skin.info:
    description: Voir le grade d'un joueur
    default: op
  site23skin.espawn:
    description: Restaurer son propre skin Mojang original
    default: true
  site23skin.espawn.other:
    description: Restaurer le skin Mojang d'un autre joueur
    default: op
